date.timezone = Europe/Paris
memory_limit = 512M
expose_php = Off

; Dev : opcache relit les fichiers modifiés
opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.max_accelerated_files = 20000
